# Generated by Django 5.0.4 on 2026-02-27 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('visitors', 'Visiteurs actifs'), ('pageviews', 'Pages vues'), ('sales', 'Ventes'), ('revenue', 'Revenus'), ('cpu', 'CPU (%)'), ('memory', 'Mémoire (%)'), ('requests', 'Requêtes/s'), ('signups', 'Inscriptions')], db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='metrics_met_metric__0f81c0_idx')],
            },
        ),
    ]
